parameters:
    env(DATABASE_PORT): '5432'
    env(DATABASE_URL): 'postgres://%env(POSTGRES_USER)%:%env(POSTGRES_PASSWORD)%@%env(DATABASE_HOST)%:%env(DATABASE_PORT)%/%env(POSTGRES_DB)%'
    env(DB_VERSION): '9.6'
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '%env(DB_VERSION)%'
        url: '%env(DATABASE_URL)%'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            NodeEnumType: App\DBAL\Types\Enum\NodeEnumType
            AccessEnumType: App\DBAL\Types\Enum\AccessEnumType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
