easy_admin:
  site_name: 'Caesar App'
  entities:
    User:
      controller: App\Controller\Admin\UserController
      class: App\Entity\User
      label: 'User'
      list:
        actions: ['resetPassword']
        title: 'Users'
        fields:
          - id
          - avatar
          - username
          - email
          - lastLogin
          - domain
          - enabled
          - srp.id
      form:
        fields:
          - enabled
          - username
          - email
          - domain
