easy_admin:
  site_name: 'Caesar App'
  entities:
    User:
      label: 'User'
      class: App\Entity\User
      disabled_actions: ['delete', 'new']
      list:
        title: 'Users'
        fields:
          - 'id'
          - 'avatar'
          - 'username'
          - 'email'
          - 'createdAt'
          - 'userDomain'
          - 'enabled'
      form:
        fields:
          - enabled
          - { property: 'username', type_options: { attr: { readonly : true } }}
          - { property: 'email', type_options: { attr: { readonly : true } }}
          - domain
