easy_admin:
  site_name: 'Caesar App'
  entities:
    User:
      controller: App\Controller\Admin\UserController
      class: App\Entity\User
      label: 'User'
      list:
        title: 'Users'
        fields:
          - id
          - avatar
          - username
          - email
          - lastLogin
          - userDomain
          - guest
          - enabled
      form:
        fields:
          - enabled
          - guest
          - username
          - email
          - userDomain
          - encryptedPrivateKey
          - publicKey
