easy_admin:
  site_name: 'Caesar App'
  entities:
    User:
      controller: App\Controller\Admin\UserController
      class: App\Entity\User
      label: 'User'
      disabled_actions: ['new']
      list:
        actions: ['resetPassword', 'reset_2fa']
        title: 'Users'
        fields:
          - id
          - username
          - roles
          - email
          - lastLogin
          - domain
          - enabled
          - srp.id
      form:
        fields:
          - enabled
          - username
          - email
          - domain
          - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true, choices: { 'user': 'ROLE_USER',  'admin': 'ROLE_ADMIN', 'read-only user': 'ROLE_READ_ONLY_USER' } } }
    UserTeam:
      class: App\Entity\UserTeam
      label: 'Users Teams'
      disabled_actions: ['new']
      list:
        title: 'Users Teams'
        fields:
          - user
          - createdAt
          - team
          - userRole
      form:
        title: 'Users Teams'
        fields:
          - { property: 'team', type: 'entity', type_options: { disabled: true } }
          - { property: 'user', type: 'entity', type_options: { disabled: true } }
          - { property: 'userRole', type: 'choice', type_options: { choices: { 'member': 'member',  'admin': 'admin' } } }
