easy_admin:
  site_name: 'Caesar App'
  entities:
    User:
      controller: App\Controller\Admin\UserController
      class: App\Entity\User
      label: 'User'
      disabled_actions: ['new']
      list:
        actions: ['resetPassword', 'reset_2fa']
        title: 'Users'
        fields:
          - id
          - username
          - roles
          - email
          - lastLogin
          - domain
          - enabled
          - srp.id
      form:
        fields:
          - enabled
          - username
          - email
          - domain
          - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true, choices: { 'user': 'ROLE_USER',  'admin': 'ROLE_ADMIN' } } }
