fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: "%env(ROBOT_EMAIL_ADDRESS)%"
        sender_name: "%env(ROBOT_EMAIL_NAME)%"
    registration:
        confirmation:
            enabled: true
        form:
            type: App\Form\RegistrationType
