fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener: true
    routing_loader: true
    view:
        view_response_listener:  'force'
    format_listener:
        rules:
            - { path: '^/api/anonymous/fido', prefer_extension: true, fallback_format: html, priorities: [ html ] } # todo: will be removed to api
            - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/status', prefer_extension: true, fallback_format: json, priorities: [ json ] }

    zone:
        - { path: ^/api }
        - { path: ^/status }
