old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(RABBITMQ_HOST)%'
            port:     5672
            user:     '%env(RABBITMQ_DEFAULT_USER)%'
            password: '%env(RABBITMQ_DEFAULT_PASS)%'
            vhost:    '%env(RABBITMQ_VHOST)%'
            lazy: true
    producers:
        send_message:
            connection:       default
            exchange_options: {name: 'send-message', type: direct}
    consumers:
        send_message:
            connection:       default
            exchange_options: {name: 'send-message', type: direct}
            queue_options:    {name: 'send-message'}
            callback:         app.send_message_consumer
            idle_timeout: 30