old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(RABBITMQ_HOST)%'
            port:     5672
            user:     '%env(RABBITMQ_DEFAULT_USER)%'
            password: '%env(RABBITMQ_DEFAULT_PASS)%'
            vhost:    '%env(RABBITMQ_VHOST)%'
#    connections:
#        default:
#            host:     "%rabbit_connection_host%"
#            port:     "%rabbit_connection_port%"
#            user:     "%rabbit_connection_user%"
#            password: "%rabbit_connection_password%"
#            vhost:    "%rabbit_connection_vhost%"
#            lazy:     "%rabbit_connection_lazy%"
#            lazy:     false
#            connection_timeout: 3
#            read_write_timeout: 3
#
#            # requires php-amqplib v2.4.1+ and PHP5.4+
#            keepalive: false
#
#            # requires php-amqplib v2.4.1+
#            heartbeat: 0

#            #requires php_sockets.dll
#            use_socket: true # default false
#        another:
#            # A different (unused) connection defined by an URL. One can omit all parts,
#            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
#            # are given the value from the URL takes precedence.
#            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
#            url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
    producers:
        send_message:
            connection:       default
            exchange_options: {name: 'send-message', type: direct}
    consumers:
        send_message:
            connection:       default
            exchange_options: {name: 'send-message', type: direct}
            queue_options:    {name: 'send-message'}
            callback:         app.send_message_consumer