# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        - Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken
    google:
        server_name: '%env(APP_NAME)%'
        enabled: true
        issuer: '%env(APP_NAME)%'
    backup_codes:
        enabled: true
