security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos.user.provider:
            id: fos_user.user_provider.username_email
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        service:
            pattern: ^/api/service
            anonymous: true
        anonymous_area:
            pattern: ^/api/anonymous
            anonymous: true
        doc:
            pattern: ^/api/doc
            http_basic: ~
            anonymous: ~
            context: admin
            provider: fos.user.provider
        admin:
            pattern: ^/admin
            http_basic: ~
            anonymous: false
            context: admin
            provider: fos.user.provider
        srp:
            pattern: ^/api/auth/srpp
            stateless: true
            context: srp
            anonymous: true
            provider:  fos.user.provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        user_bootstrap:
            pattern: ^/api/user/security/bootstrap
            stateless: true
            context: user_bootstrap
            anonymous: ~
            provider:  fos.user.provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        api:
            pattern: ^/api
            provider: fos.user.provider
            stateless: true
            anonymous: ~
            two_factor:
                check_path: /api/auth/2fa
                provider: fos.user.provider
                auth_code_parameter_name: authCode
                success_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                failure_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                authentication_required_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: fos.user.provider
            logout: true
            stateless: false
            anonymous: true
            oauth:
                resource_owners:
                    google: google_login
                login_path: /login
                provider: hwi_oauth.user.provider
                oauth_user_provider:
                    service: App\Security\FOSUBUserProvider
                failure_handler: App\Security\Authentication\OAuthFailureHandler
                success_handler: App\Security\JwtRedirectHandler
    access_control:
        - { path: ^/api/share/messages, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/message, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/service, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/anonymous, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/auth, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/user/self, roles: [IS_AUTHENTICATED_FULLY], methods: [GET] }
        - { path: ^/api, roles: [ROLE_USER]}
        - { path: ^/api/doc, roles: [ROLE_SUPER_ADMIN]}
        - { path: ^/admin, roles: [ROLE_ADMIN]}
