security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider
        in_memory:
            memory:
                users:
                    admin:
                        password:            '%env(SUPERADMIN_PASS)%'
                        roles:               ROLE_ADMIN
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        doc:
            pattern: ^/doc
            http_basic: ~
            anonymous: ~
            context: admin
            provider: in_memory
        admin:
            pattern: ^/admin
            http_basic: ~
            anonymous: ~
            context: admin
            provider: in_memory
        api:
            pattern: ^/api
            provider:  fos_userbundle
            stateless: true
            anonymous: ~
            two_factor:
                check_path: /api/2fa_check
                provider: fos_userbundle
                success_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                failure_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                authentication_required_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout: true
            stateless: false
            anonymous: true
            oauth:
                resource_owners:
                    google: google_login
                login_path: /login
                provider: hwi_oauth.user.provider
                oauth_user_provider:
                    service: App\Security\FOSUBUserProvider
                failure_handler: App\Security\Authentication\OAuthFailureHandler
                success_handler: App\Security\JwtRedirectHandler
    access_control:
        - { path: ^/api/share/messages, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: "^/api/share/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$", methods: ["GET"], roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api, roles: [ROLE_USER]}
        - { path: ^/doc, roles: [ROLE_ADMIN]}
        - { path: ^/admin, roles: [ROLE_ADMIN]}
