security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt
    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER
        ROLE_SYSTEM_USER: ROLE_USER
    providers:
        fos.user.provider:
            id: fos_user.user_provider.username_email
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider
        cache_user_provider:
            id: App\Security\Provider\SystemUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        service:
            pattern: ^/api/service
            anonymous: true
        anonymous_area:
            pattern: ^/api/anonymous
            anonymous: true
        admin:
            pattern: ^/(admin|api/srp_login_confirm|2fa_check)
            logout: true
            stateless: false
            anonymous: false
            context: main
            two_factor:
                provider: fos.user.provider
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                prepare_on_login: true
                auth_code_parameter_name: authCode
                success_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                failure_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
            guard:
                provider: fos.user.provider
                authenticators:
                    - App\Security\Authentication\SrppAuthenticator
        srp:
            pattern: ^/api/auth/srpp
            stateless: true
            context: srp
            anonymous: true
            provider:  fos.user.provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        user_bootstrap:
            pattern: ^/api/user/security/bootstrap
            stateless: true
            context: user_bootstrap
            anonymous: ~
            provider:  fos.user.provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        api_security_messages:
            pattern: ^/api/message
            anonymous: true
        api:
            pattern: ^/api
            logout: true
            provider: fos.user.provider
            stateless: false
            anonymous: ~
            two_factor:
                check_path: /api/auth/2fa
                provider: fos.user.provider
                prepare_on_login: true
                auth_code_parameter_name: authCode
                success_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                failure_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
                authentication_required_handler: App\Security\Authentication\TwoFactorAuthenticationHandler
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        json_rpc:
            pattern: ^/json-rpc
            stateless: true
            provider: cache_user_provider
            guard:
                authenticators:
                    - App\Security\Authentication\TokenAuthenticator
        main:
            pattern: ^/
            logout: true
            stateless: false
            anonymous: true
            guard:
                provider: fos.user.provider
                authenticators:
                    - App\Security\Authentication\SrppAuthenticator
            oauth:
                resource_owners:
                    google: google_login
                login_path: /login
                provider: hwi_oauth.user.provider
                oauth_user_provider:
                    service: App\Security\FOSUBUserProvider
                failure_handler: App\Security\Authentication\OAuthFailureHandler
                success_handler: App\Security\JwtRedirectHandler
    access_control:
        - { path: ^/json-rpc, roles: [ROLE_SYSTEM_USER]}
        - { path: ^/api/share/messages, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/message, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/service, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/anonymous, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/srp_login_confirm, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/auth, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api/users/self, roles: [IS_AUTHENTICATED_ANONYMOUSLY], methods: [GET] }
        - { path: ^/api/doc, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/api, roles: [ROLE_USER]}
        - { path: ^/admin, roles: [ROLE_ADMIN]}
