sylius_mailer:
    sender:
        name: '%env(APP_NAME)%'
        address: '%env(SENDER_ADDRESS)%'
    emails:
        !php/const App\Mailer\MailRegistry::INVITE_SEND_MESSAGE:
            subject: 'You’ve been invited to join %env(APP_NAME)%'
            template: email/invite_message.html.twig
        !php/const App\Mailer\MailRegistry::SHARE_SEND_MESSAGE:
            subject: 'Shared access with you'
            template: email/share_message.html.twig
        !php/const App\Mailer\MailRegistry::NEW_ITEM_MESSAGE:
            subject: 'You got access to new secure data'
            template: email/new_item_message.html.twig

