sylius_mailer:
    sender:
        name: '%env(DELIVERY_NAME)%'
        address: '%env(SENDER_ADDRESS)%'
    emails:
        !php/const App\Mailer\MailRegistry::INVITE_SEND_MESSAGE:
            subject: 'Shared access with you'
            template: email/invite_message.html.twig
        !php/const App\Mailer\MailRegistry::SHARE_SEND_MESSAGE:
            subject: 'Shared access with you'
            template: email/share_message.html.twig
