kind: secret
name: username
get:
  path: caesar-team/data/registry
  name: username
---
kind: secret
name: password
get:
  path: caesar-team/data/registry
  name: password
---
kind: secret
name: repository
get:
  path: caesar-team/data/registry
  name: repo-server
---
kind: secret
name: registry
get:
  path: secret/data/registry
  name: registry
---
kind: secret
name: develop_url
get:
  path: secret/data/k8s-4xxi
  name: develop_url
---
kind: secret
name: develop_token
get:
  path: secret/data/k8s-4xxi
  name: develop_token
---
kind: secret
name: develop_ca
get:
  path: secret/data/k8s-4xxi
  name: develop_ca
---
kind: secret
name: staging_url
get:
  path: secret/data/k8s-4xxi
  name: staging_url
---
kind: secret
name: staging_token
get:
  path: secret/data/k8s-4xxi
  name: staging_token
---
kind: secret
name: staging_ca
get:
  path: secret/data/k8s-4xxi
  name: staging_ca
---
kind: secret
name: notifications
get:
  path: secret/data/notifications-4xxi
  name: caesar-builds
---
kind: secret
name: notification_username
get:
  path: secret/data/notifications-4xxi
  name: username
---
kind: secret
name: notification_icon
get:
  path: secret/data/notifications-4xxi
  name: icon_url
---
kind: pipeline
type: docker
name: 4xxi

services:
  - database:
    name: test database
    image: postgres:9
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'

globals:
- &confNoSaveBuild
  dockerfile: Dockerfile
  repo: check_build
  dry_run: true
  purge: false
  tag: fourxxi
  daemon_off: false

- &confSaveBuild
  dockerfile: Dockerfile
  repo: 
    from_secret: repository
  tag: ${DRONE_BRANCH}
  username:
    from_secret: username
  password:
    from_secret: password

- &stepRunTests
  name: run tests
  image: check_build:fourxxi
  pull: never
  context: /var/www/html
  environment:
    APP_ENV: 'test'
  commands:
    - cd /var/www/html
    - pwd
    - ls -la
    - ls -la bin
    - ls -la /var/www/html/vendor
    - bin/console doctrine:migrations:migrate --env=test
    - bin/codecept build
    - bin/codecept run api

- &stepCheckBuild
  name: check build
  image: plugins/docker
  volumes:
  - name: dockersocket
    path: /var/run/docker.sock
  settings:
    <<: *confNoSaveBuild

- &stepMainBuild
  name: build
  image: plugins/docker
  settings:
    <<: *confSaveBuild

- &stepDevelopDeploy
  name: deploy develop
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: develop_url
    kubernetes_token:
      from_secret: develop_token
    kubernetes_cert:
      from_secret: develop_ca
  environment:
    CICD_GIT_COMMIT: ${DRONE_COMMIT}
    CICD_GIT_BRANCH: ${DRONE_BRANCH}
  commands:
  - sed -i "s/\$CICD_GIT_BRANCH/$CICD_GIT_BRANCH/g" k8s/deployment.yaml
  - sed -i "s/\$CICD_GIT_COMMIT/$CICD_GIT_COMMIT/g" k8s/deployment.yaml
  - kubectl apply -f k8s/deployment.yaml

- &stepMasterDeploy
  name: deploy staging
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: staging_url
    kubernetes_token: 
      from_secret: staging_token
    kubernetes_cert: 
      from_secret: staging_ca
  environment:
    CICD_GIT_COMMIT: ${DRONE_COMMIT}
    CICD_GIT_BRANCH: ${DRONE_BRANCH}
  commands:
  - sed -i "s/\$CICD_GIT_BRANCH/$CICD_GIT_BRANCH/g" k8s/deployment.yaml
  - sed -i "s/\$CICD_GIT_COMMIT/$CICD_GIT_COMMIT/g" k8s/deployment.yaml
  - kubectl apply -f k8s/deployment.yaml

- &stepNotifyToSlack
  name: notify-to-slack
  image: plugins/slack
  pull: always
  settings:
    webhook:
      from_secret: notifications
    channel: caesar-builds
    username: 
      from_secret: notification_username
    icon_url:
      from_secret: notification_icon
    template: >
      {{#success build.status}}
       *Event*: `{{build.event}}` {{build.status}}
       *Repository*: `{{repo.name}}` to `{{build.branch}}`
       *Commit*: `{{build.commit}}`
       *Info*: {{build.number}} build was started {{since build.created}} and executed for {{since build.started}}
      <{{build.link}}|*Build link*>
      {{else}}
       *Event*: `{{build.event}}` {{build.status}}
       *Repository*: `{{repo.name}}` to `{{build.branch}}`
       *Commit*: `{{build.commit}}`
       *Info*: {{build.number}} build was started {{since build.created}} and executed for {{since build.started}}
      <{{build.link}}|*Build link*>
      {{/success}}

steps:
- <<: *stepCheckBuild
  when:
    branch: [ feature/* ]

- <<: *stepMainBuild
  when:
    branch: [ develop, master ]

- <<: *stepRunTests
  when:
    branch: [ feature/* ]

- <<: *stepDevelopDeploy
  when:
    branch: [ develop ]

- <<: *stepMasterDeploy
  when:
    branch: [ master ]

- <<: *stepNotifyToSlack
  when:
    status: [ success, failure ]
    branch: [ develop, master ]

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - master
  - develop
  - feature/*

