stages:
- name: Publish image
  steps:
  - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        pushRemote: true
        tag: caesarteam/caesar-server:${CICD_GIT_BRANCH}
        registry: index.docker.io
- name: Object update ConfigMap
  steps:
  - applyYamlConfig:
        path: ./deploy/configmap.yaml
- name: Object update Deployment
  steps:
  - applyYamlConfig:
        path: ./deploy/deployment.yaml
- name: Object update CronJob
  steps:
  - applyYamlConfig:
        path: ./deploy/cronjob.yaml
branch:
  include: [ develop, master ]
notification:
  recipients:
  - recipient: "#caesarapp-notify"
    notifier: "slack"
  condition: [ Success, Changed, Failed ]
