stages:
- name: Publish image
  steps:
  - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: caesarteam/caesar-server:${CICD_GIT_BRANCH}
        registry: docker-registry
- name: Deploy
  steps:
  - applyYamlConfig:
        path: ./deploy/deployment.yaml
# branch conditions for the pipeline
branch:
    include: [develop]
