stages:
- name: Publish image
  steps:
  - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        pushRemote: true
        tag: caesarteam/caesar-server:${CICD_GIT_BRANCH}
        registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
        path: ./deploy/deployment.yaml
branch:
  include: [ develop, master ]
notification:
  recipients:
  - recipient: "#caesarapp-notify"
    notifier: "slack"
  condition: [ Success, Changed, Failed ]
