version: '3.2'

services:
    php:
        build: .
        volumes:
            - .:/var/www/html
        expose:
            - 9000
        environment:
            - PARENT_USER_ID
            - APP_ENV
            - JWT_PASSPHRASE
        user: "$UID:$UID"
        depends_on:
            - db
            - redis
            - rabbitmq
        entrypoint:
            - "./entrypoint.sh"
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: "postgres:9"
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    db_test:
        image: postgres:9
        ports:
            - "5433:5432"
        command: ["postgres", "-c", "fsync=off", "-c", "full_page_writes=off"]
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    redis:
        image: 'redis:5-alpine'
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        volumes:
            - "redis:/etc/redis/database/caesarapp"
    rabbitmq:
        image: "rabbitmq:3-management-alpine"
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_VHOST
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - "rmq:/var/lib/rabbitmq"
volumes:
    db:
    redis:
    rmq:
