version: '3.2'

services:
    web:
        image: caesarteam/caesar-server:develop
        expose:
            - 8080
        depends_on:
            - db
            - redis
            - rabbitmq
        entrypoint:
            - "./entrypoint.sh"
    db:
        image: "postgres:9"
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    redis:
        image: 'redis:6-alpine'
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        volumes:
            - "redis:/etc/redis/database/caesarapp"
    rabbitmq:
        image: "rabbitmq:3-management-alpine"
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_VHOST
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - "rmq:/var/lib/rabbitmq"
volumes:
    db:
    redis:
    rmq:
