version: '3.2'

services:
    php:
        image: 51a5f9467b2a
        expose:
        - 9000
        environment:
        - APP_ENV=prod
        env_file:
        - .env
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: postgres:9
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    db_test:
        image: postgres:9
        ports:
            - "5433:5432"
        command: ["postgres", "-c", "fsync=off", "-c", "full_page_writes=off"]
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
volumes:
    db:
    trash:
