version: '3.2'

services:
    rr:
        container_name: "rr"
        build:
          context: .
          dockerfile: containers/roadrunner/Dockerfile
        ports:
          - 8080:8080
        volumes:
            - .:/var/www/html
            - ./etc/roadrunner:/etc/roadrunner
        environment:
            - PARENT_USER_ID
            - APP_ENV
            - JWT_PASSPHRASE
        user: "$UID:$UID"
        depends_on:
            - db
            - redis
            - rabbitmq
    db:
        image: "postgres:9"
        ports:
            - "${DATABASE_PORT}:${DATABASE_PORT}"
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
    redis:
        image: 'redis:5-alpine'
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        volumes:
            - "redis:/etc/redis/database/caesarapp"
    rabbitmq:
        image: "rabbitmq:3-management-alpine"
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS
            - RABBITMQ_VHOST
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - "rmq:/var/lib/rabbitmq"
volumes:
    db:
    redis:
    rmq:
