apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-message-consumer
  namespace: default
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-message-history
            image: "caesarteam/caesar-server:develop"
            command: ["/usr/local/bin/php", "bin/console", "rabbitmq:consumer", "send_message", "-e", "prod", "-m", "${RABBITMQ_MAX_COUNT}"]
            envFrom:
            - configMapRef:
                name: caesar-server-config
            - secretRef:
                name: caesar-server-secret
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-secret
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-clear-message-history
  namespace: default
spec:
  schedule: "0 12 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-message-history
            image: "caesarteam/caesar-server:develop"
            command: ["/usr/local/bin/php", "bin/console", "app:clear-message-history", "-e", "prod"]
            envFrom:
            - secretRef:
                name: caesarapp-secret
          restartPolicy: OnFailure
