apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: default
data:
  RABBITMQ_DEFAULT_PASS: cmFiYml0bXE=
  RABBITMQ_DEFAULT_USER: cmFiYml0bXE=
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      name: rabbitmq-server
  clusterIP: None
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-alpine
        env:
          - name: RABBITMQ_VHOST
            value: /
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                key: RABBITMQ_DEFAULT_USER
                name: rabbitmq
                optional: false
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                key: RABBITMQ_DEFAULT_PASS
                name: rabbitmq
                optional: false
        ports:
          - containerPort: 5672
            name: rabbitmq-server
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
      namespace: default
      labels:
        app: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 1Gi
