monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: '%env(LOGGING_LEVEL)%'
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "php://stderr"
            level: '%env(LOGGING_LEVEL)%'
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
