google_login:
    path: /login/google
google_connect:
    path: /connect/google

_security_logout:
    path: /logout
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_resetting_reset:
    path: /api/auth/srpp/reset/{token}
    defaults: { _controller: App\Controller\Api\SrpController:resetPassword }
    methods: ["PATCH"]
