_login:
    path: /login
google_login:
    path: /login/google
google_connect:
    path: /connect/google

2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"
2fa_login_check:
    path: /2fa_check

_security_logout:
    path: /logout
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_resetting_reset:
    path: /api/auth/srpp/reset/{token}
    defaults: { _controller: App\Controller\Api\SrpController:resetPassword }
    methods: ["PATCH"]
fos_user_resetting_request:
    path: /api/auth/request
    defaults: { _controller: fos_user.resetting.controller:requestAction }
    methods: ["GET"]
fos_user_resetting_send_email:
    path: /api/auth/send-email
    defaults: { _controller: fos_user.resetting.controller:sendEmailAction }
    methods: ["POST"]
fos_user_resetting_check_email:
    path: /api/auth/check-email
    defaults: { _controller: fos_user.resetting.controller:checkEmailAction }
    methods: ["GET"]
