services:
    _defaults:
        public: true
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: [doctrine.fixture.orm]
    test.client:
        class: 'App\Tests\Client'
        arguments:
            - '@kernel'
            - ['@test.client.history']
    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface: '@lexik_jwt_authentication.jwt_manager'

    App\Notification\MessengerInterface: '@App\Notification\DatabaseMessenger'
